# Generated by Django 3.2 on 2022-12-31 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0002_auto_20221231_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_compañia', models.CharField(max_length=200)),
                ('nombre_representante', models.CharField(max_length=200)),
                ('telefono_representante', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(default=27963741),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='tienda/cliente/images/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tienda/productos/images/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.proveedor'),
        ),
    ]
