# Generated by Django 3.2 on 2022-12-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_producto_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente de envío', 'Pendiente de envío'), ('Procesando', 'Procesando'), ('Enviado', 'Enviado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Procesando', max_length=50),
        ),
    ]
