# Generated by Django 3.2 on 2022-12-31 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_pedido_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='total',
            new_name='monto_total',
        ),
    ]
