# Generated by Django 3.2 on 2022-12-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_pedido_cod_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente de envío', 'Pendiente de envío'), ('Pedido en preparación', 'Pedido en preparación'), ('Pedido aceptado', 'Pedido aceptado'), ('Enviado', 'Enviado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Pedido aceptado', max_length=50),
        ),
    ]
