# Generated by Django 3.2 on 2022-12-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock mínimo'),
        ),
    ]
