# Generated by Django 3.2 on 2022-12-31 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_alter_producto_stock_min'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre_compañia',
            new_name='nombre_empresa',
        ),
    ]
