# Generated by Django 3.2 on 2023-03-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_alter_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('en_venta', 'en venta'), ('pausado', 'pausado'), ('eliminado', 'eliminado')], default='en_venta', max_length=255),
        ),
    ]
