# Generated by Django 3.2 on 2023-03-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0018_alter_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('activo', 'activo'), ('pausado', 'pausado'), ('eliminado', 'eliminado')], default='activo', max_length=255),
        ),
    ]
