# Generated by Django 3.2 on 2023-01-02 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_auto_20230101_2345'),
        ('turnero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.servicio'),
        ),
    ]
