# Generated by Django 3.2 on 2023-03-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0004_auto_20230323_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='confirmado', max_length=20),
        ),
    ]
