# Generated by Django 3.2 on 2022-12-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20221231_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creado_en',
            field=models.DateTimeField(),
        ),
    ]
