# Generated by Django 3.2 on 2022-12-31 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20221231_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='nombre',
        ),
    ]
