# Generated by Django 3.2 on 2023-02-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20230207_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='estado',
            new_name='estado_mensaje',
        ),
    ]
