# Generated by Django 3.2 on 2023-02-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_estado_mensaje_estado_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(default='sdas', max_length=200),
            preserve_default=False,
        ),
    ]
