# Generated by Django 3.2 on 2022-12-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='cuerpo',
            field=models.CharField(default='lorem lorem lorem lorem', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagen',
            name='estado',
            field=models.CharField(choices=[('publicar', 'Publicar'), ('no_publicar', 'No Publicar')], default='publicar', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagen',
            name='imagen_destacada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='creado_en',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
