# Generated by Django 3.2 on 2022-12-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_auto_20221231_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='estado',
            field=models.CharField(choices=[('publicar', 'Publicar'), ('no_publicar', 'No Publicar')], default='publicar', max_length=255),
        ),
    ]
