# Generated by Django 3.2 on 2023-01-02 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_cliente_telefono'),
        ('ordenes', '0002_orden_servicio_servicioxorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioxorden',
            name='cant_prod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicioxorden',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
        ),
    ]
